version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    tty: true
  frontend:
    image: node:16-bullseye
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app/frontend
    command: yarn start
