version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    tty: true
    depends_on:
      - db

  frontend:
    image: node:16-bullseye
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app/frontend
    command: yarn start

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - db-data:/var/lib/mysql
  
volumes:
  db-data:
    driver: local
